### ISSUE TITLE
Resolving did:indy:sov yields Error: A value must be provided for the 'pool' parameter

### ISSUE THREAD

**Issue by dennisn00** [decentralized-identity/uni-resolver-driver-did-indy#3]
I set up this Project in Docker as described in the Readme and ran curl with `did:indy:sovrin:WRfXPg8dantKVubE3HX8pw` (the example given).
This ran for several minutes until it returned the error `A value must be provided for the 'pool' parameter`.
During the resolving, the logs showed a Timeout for ledger Operation happening on sovrin and bbu:
`Cannot open pool "sovrin": org.hyperledger.indy.sdk.ledger.TimeoutException: Timeout happens for ledger operation` (same error for bbu).
I am not sure why there even is an attempt to open the bbu pool for a did:indy:sovrin.

Also, it seems like the pool configuration is set up correctly (unlike a [similar Issue](https://github.com/decentralized-identity/universal-resolver/issues/390) I opened on the Universal Resolver Project yesterday). In the logs it says
```
Loading from environment
{PATH=[...], LANGUAGE=[...], JETTY_BASE=/var/lib/jetty, 
uniresolver_driver_did_indy_poolConfigs=sovrin;./sovrin/sovrin.txn;sovrin:staging;./sovrin/sovrin-staging.txn;sovrin:builder;./sovrin/sovrin-builder.txn;danube;./sovrin/danube.txn;idunion;./sovrin/idunion.txn;idunion:test;./sovrin/idunion-test.txn;indicio;./sovrin/indicio.txn;indicio:test;./sovrin/indicio-test.txn;indicio:demo;./sovrin/indicio-demo.txn;bbu;./sovrin/bbu.txn;nxd;./sovrin/nxd.txn;findy:test;./sovrin/findy-test.txn,
JETTY_TGZ_URL=[...], JAVA_HOME=[...], 
uniresolver_driver_did_indy_libIndyPath=, 
LANG=[...], JETTY_GPG_KEYS=[...], 
uniresolver_driver_did_indy_poolVersions=sovrin;2;sovrin:staging;2;sovrin:builder;2;danube;2;idunion;2;idunion:test;2;indicio;2;indicio:test;2;indicio:demo;2;bbu;2;nxd;2;findy:test;2, 
TMPDIR=[...], uniresolver_driver_did_indy_submitterDidSeeds=sovrin;_;sovrin:staging;_;sovrin:builder;_;danube;_;idunion;_;idunion:test;_;indicio;_;indicio:test;_;indicio:demo;_;bbu;_;nxd;_;findy:test;_, 
HOSTNAME=[...], LC_ALL=[...], JETTY_HOME=[...], JETTY_VERSION=11.0.17, 
uniresolver_driver_did_indy_walletNames=sovrin;w1;sovrin:staging;w2;sovrin:builder;w3;danube;w4;idunion;w5;idunion:test;w6;indicio;w7;indicio:test;w8;indicio:demo;w9;bbu;w10;nxd;w11;findy:test;w12, 
PWD=[...], JAVA_VERSION=[...], HOME=[...]}
```

I tried resolving `did:indy:idunion:BNrX6yZzHkKbBGv5aX6PR4` and it worked, so the problem seems to be with the sovrin pool.

I also tried adding a local von-network ledger by adding the genesis txn file and appending the poolConfig, poolVersions and so on, with the same result: `A value must be provided for the 'pool' parameter`.

**Comment by peacekeeper** [comment]
Hello, I just removed the "bbu" network in https://github.com/decentralized-identity/uni-resolver-driver-did-indy/commit/95e4b959fcc33c792edd0a67d93d56f83eb9a46b and https://github.com/decentralized-identity/uni-resolver-driver-did-sov/commit/141e6c7f6bb4d6f198e98b6d9c1c7349bca9a914.

With regard to the "sovrin" pool, we will investigate a bit more.

**Comment by peacekeeper** [comment]
Hello again, we updated the sovrin pool file in https://github.com/decentralized-identity/uni-resolver-driver-did-indy/commit/aaf7add93e4e41bb69a3d73b326ad1c0be65e51d, could you try again if it works now?

**Comment by dennisn00** [comment]
Yes, it works now! I had the same problem when trying to resolve a DID in a von-network running in a local docker. May I assume that the problem lies in the von-network genesis file/the network configuration, and not the indy driver?

**Comment by peacekeeper** [comment]
Yes maybe.. I have never tried it with a local von-network. But running Indy inside Docker can have some challenges with regard to host and guest IP addresses, exposing ports, etc.

**Comment by dennisn00** [comment]
I was able to figure out the problem with the von-network. Basically, I had to start the von-network with`./manage start <ip_address_of_host_machine>`. Maybe it would be helpful to others to add a short section about using the von-network together with this Driver to the documentation (I could do that)?

**Comment by peacekeeper** [comment]
> Maybe it would be helpful to others to add a short section about using the von-network together with this Driver

Good to hear you managed to make it work. I agree such a section would be helpful!

**Comment by dennisn00** [comment]
Documentation for usage with the von-network [was added](https://github.com/decentralized-identity/uni-resolver-driver-did-indy/pull/6)
